# @baseUrl = https://kasirv1.zeabur.app
@baseUrl = http://localhost:8080

### Health Check
GET {{baseUrl}}/health

### Get All Products
GET {{baseUrl}}/api/produk

### Search Products by Name
GET {{baseUrl}}/api/produk?name=Jeruk

### Create Product (Juice)
POST {{baseUrl}}/api/produk
Content-Type: application/json

{
    "name": "Es Jeruk Peras",
    "price": 8000,
    "stock": 100,
    "category_id": 1
}

### Create Product (Fried Rice)
POST {{baseUrl}}/api/produk
Content-Type: application/json

{
    "name": "Nasi Goreng Spesial",
    "price": 20000,
    "stock": 30,
    "category_id": 2
}

### Get Product by ID
GET {{baseUrl}}/api/produk/1

### Update Product
PUT {{baseUrl}}/api/produk/1
Content-Type: application/json

{
    "name": "Kopi Hitam (Update)",
    "price": 12000,
    "stock": 80,
    "category_id": 1
}

### Checkout / Transaction
POST {{baseUrl}}/api/checkout
Content-Type: application/json

{
    "items": [
        {
            "product_id": 1,
            "quantity": 2
        },
        {
            "product_id": 2,
            "quantity": 1
        }
    ]
}

### Sales Summary Hari Ini
GET {{baseUrl}}/api/report/hari-ini

### Sales Report by Range
GET {{baseUrl}}/api/report?start_date=2026-02-01&end_date=2026-02-28

### Delete Product
DELETE {{baseUrl}}/api/produk/1
