services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kasir-api-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "8080"
      DB_CONN: "postgres://kasir:kasir@db:5432/kasir_db?sslmode=disable"
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: kasir-api-db
    environment:
      POSTGRES_USER: kasir
      POSTGRES_PASSWORD: kasir
      POSTGRES_DB: kasir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kasir -d kasir_db"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

volumes:
  postgres_data:
